image: node

before_script:
  - pwd

pages:
  script:
    - cd public-website
    - npm --version
    - date
    - yarn install
    - date
    - yarn run generate
    - date 
    - du -sh public/
    - mv public ../public
    - ls -a 
    - pwd 
    - cd .. 
    - ls -a 
    - pwd
  artifacts:
    paths:
      - public

