pages:
  image: node
  before_script:
    - pwd
  script:
    - cd src/public-website
    - npm --version
    - date
    - yarn install
    - date
    - yarn run build
    - date
    - du -sh dist/
    - mv dist ../../public
    - ls -a
    - pwd
    - cd ..
    - ls -a
    - pwd
  artifacts:
    paths:
      - public
