version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro,z"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro,z"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro,z"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro,z"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw,z"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  backend:
    restart: always
    build: ./public-backend
    container_name: public-backend
    environment:
      - VIRTUAL_HOST=api.wyoming.liftrocket.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.wyoming.liftrocket.com
      - LETSENCRYPT_EMAIL=kushaldeveloper@gmail.com

  website:
    restart: always
    image: website
    build: ./built-website
    container_name: built-website
    volumes:
      - "./volumes/nginx-website/conf.d/:/etc/nginx/conf.d:z"
    environment:
      - VIRTUAL_HOST=web.wyoming.liftrocket.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=web.wyoming.liftrocket.com
      - LETSENCRYPT_EMAIL=kushaldeveloper@gmail.com
